### ISSUE TITLE
No warning when leaving profile editing page without saving

### ISSUE THREAD

**Issue by jesseallhands** [Couchers-org/couchers#2045] opened 2021-10-03 01:30 UTC
Currently if you are editing your profile and try to leave the page without saving first, there is no warning to let you know that you will lose all of the information you entered. This is resulting in very frustrated users who spend a lot of time filling out their profile and they lose it all because they clicked somewhere else before saving.

Could we add a warning dialog box to alert users that if they leave they will lose all unsaved data?

"Are you sure you want to leave this page without saving? If you want to save before leaving, click "save".

[leave page without saving] [save]

**Comment by aapeliv** [comment] 2021-10-03 01:30
Dupe of #1635

**Closed as completed by aapeliv** 2021-10-03 01:30 UTC
Labels: 1.topic frontend, improvement
