### ISSUE TITLE
The first time the dashboard loads, it's scrolled down halfway

### ISSUE THREAD

**Issue by aapeliv** [Couchers-org/couchers#1276] opened 2021-05-23 14:32 UTC
I've noticed this a few times: when the dashboard loads the first time after signing up (not logging in), it's scrolled halfway down the page (so the "Welcome to the Couchers.org Beta!") isn't visible.

**Comment by thdk** [comment] 2021-08-16 20:18
Closing this, can't reproduce on chrome both desktop/android. Feel free to reopen if problem still exists.

**Closed as completed by thdk** 2021-08-16 20:18 UTC
Labels: 0.kind bug report, 1.topic frontend
