### ISSUE TITLE
[login page] design descrepancies

### ISSUE THREAD

**Issue by cmtcosta** [Couchers-org/couchers#969] opened 2021-04-04 15:37 UTC
### Environment
iPhone 8 / browser: Safari

### Steps to repro
1. Access https://develop--frontend.preview.coucher.org/
2. Click "Log in" button

### Expected results
![image](https://user-images.githubusercontent.com/6439724/113513757-16b20b00-9563-11eb-8f63-1e603902cdc0.png)

### Actual results
<img src="https://user-images.githubusercontent.com/6439724/113513790-334e4300-9563-11eb-94fb-5bfaf2d2127f.PNG" width="300">

- ~~missing "Password" field~~
- ~~missing "-- or --" separator~~
- ~~missing "Login with facebook" and "Login with google" buttons~~
- "No account yet? Sign up" link is hidden by unnecessary spacing (need to scroll down to render it visible)

**Comment by darrenvong** [comment] 2021-04-05 00:04
> missing "Password" field

This is intentional, since not all users have a password set. Pressing "continue" checks that and shows the password field if they have one.

> missing "-- or --" separator
missing "Login with facebook" and "Login with google" buttons

These are irrelevant for now as we aren't supporting Facebook/Google auth for the time being.


So the only bug here as far as I'm concerned is the last point.

**Comment by cmtcosta** [comment] 2021-04-05 08:35
Fair enough, thanks for looking into this @darrenvong !

**Comment by thdk** [comment] 2021-04-10 05:19
Duplicate of #966

**Comment by darrenvong** [comment] 2021-04-10 21:18
@thdk good spot! I'll close the other one since I commented here so whoever works on this knows to only the fix the scroll problem

**Comment by lucaslcode** [comment] 2021-05-14 22:47
This was fixed

**Closed as completed by lucaslcode** 2021-05-14 22:47 UTC
Labels: 1.topic frontend, mobile
