### ISSUE TITLE
Error on login attempt with wrong password

### ISSUE THREAD

**Issue by aapeliv** [Couchers-org/couchers#531] opened 2021-01-26 00:04 UTC
<img width="977" alt="Screen Shot 2021-01-25 at 7 02 39 pm" src="https://user-images.githubusercontent.com/2975660/105781132-f8ff6e80-5f3f-11eb-967a-77b7ffca80c9.png">

1. Try login with `test`
2. Enter wrong password.
3. You get an error: `Reads "can't access property "getResponseMessage", e is undefined".`

**Comment by lucaslcode** [comment] 2021-01-26 21:39
I suspect this is the same reason as #481, giving an "unauthenticated" error which triggers a log out, which fails because you aren't logged in. However I don't know why you then get that error, we don't call that function anywhere.

**Comment by lucaslcode** [comment] 2021-01-26 21:40
https://github.com/Couchers-org/couchers/blob/34cf62f4cd3d7dc75d0fd0717e78effe0d7b8d5d/app/backend/src/couchers/servicers/auth.py#L344 Errors in this function should be NOT_FOUND or something else

**Comment by ShmuelTreiger** [comment] 2021-01-27 05:23
When I try to login with test, I get invalid username/password. Could you add more steps to reproduce?

![image](https://user-images.githubusercontent.com/14131043/105946751-bb244800-601c-11eb-866b-3c909f3666f8.png)

**Comment by ShmuelTreiger** [comment] 2021-01-27 09:45
Brief googling tells me this is probably a frontend problem

https://www.google.com/search?q=can%27t+access+property+e+is+undefined&oq=can%27t+access+property+e+is+undefined&aqs=chrome..69i57j0i22i30l4.8719j1j7&sourceid=chrome&ie=UTF-8

**Comment by lucaslcode** [comment] 2021-01-27 10:24
Yes and no, there's two issues.

The first is the frontend treats the UNAUTHENTICATED error code to mean a user has tried to access something without being logged in. Since the login session uses secure cookies which can't be access in JS, we just have a variable `isAuthenticated` which is set to true on login and false on log out. However the cookie might expire, or the backend might log us out, so next time we try to make an API call, we get UNAUTHENTICATED, so we know to set `isAuthenticated` to false. This happens in an API interceptor. .

So that error code is not really relevant for an incorrect password, because it's a kind of failure rather than trying to access something without being logged in, if that makes sense. 

The other problem is what the error message says, which is a frontend problem. But I think it's a gRPC library issue or related to how interceptors, because our code doesn't call `getResponseMethod` anywhere. And changing the above issue should fix this bug anyway.

**Comment by aapeliv** [comment] 2021-01-27 23:48
@ShmuelTreiger: this is on the new react frontend https://develop--frontend.preview.coucher.org/

**Comment by ShmuelTreiger** [comment] 2021-02-01 21:49
@aapeliv I see it now, thought something's changed because the message is slightly different
![image](https://user-images.githubusercontent.com/14131043/106522123-0fec1680-6494-11eb-8f60-d5f53746be6f.png)

@lucaslcode I understand everything about the authentication, but I don't understand why that would cause the front end to display this error message. In any event, it should be fixed soon enough if it's actually caused by the same bug.

**Comment by lucaslcode** [comment] 2021-02-02 00:37
@ShmuelTreiger I figured it out! It's my fault. On [this line](https://github.com/Couchers-org/couchers/blob/69c27faeea54f6e6084ac8bea67d34f1cdb0f580/app/frontend/src/features/auth/useAuthStore.ts#L134), I forgot to `await` the service call, which is asynchronous.

You can put that in your PR too if  you want, or I can do it later. Just change that line to   
`await service.user.logout();`

With that fix, instead what happens is the message "You were logged out." is displayed at the start login page, which is what is supposed to happen when the server logs you out

**Comment by ShmuelTreiger** [comment] 2021-02-02 00:52
Either way, up to you

**Comment by lucaslcode** [comment] 2021-02-02 09:59
Maybe put it in then, since it's part of this issue

**Comment by aapeliv** [comment] 2021-02-04 21:09
Is this closed @lucaslcode?

**Comment by lucaslcode** [comment] 2021-02-04 23:27
Closed in #534

**Closed as completed** 2021-02-04 23:26 UTC
Labels: 0.kind bug report, 1.topic backend, 3.skill good first issue, 1.topic frontend
