### ISSUE TITLE
[signup page] missing elements

### ISSUE THREAD

**Issue by cmtcosta** [Couchers-org/couchers#966] opened 2021-04-04 14:41 UTC
### Environment
iPhone 8 / browser: Safari

### Steps to repro

1. Access  https://develop--frontend.preview.coucher.org/ 
2. Press “Sign up”

### Expected results
![image](https://user-images.githubusercontent.com/6439724/113512321-00548100-955c-11eb-8aa5-e31985879cdd.png)

### Actual results
![IMG_6879](https://user-images.githubusercontent.com/6439724/113512336-1104f700-955c-11eb-969b-901a571dd9ac.PNG)
- KO Missing elements: “password”, “confirm password”, “sign up with Facebook”, “sign up with google”
- KO Unnecessary scroll hides “Already have an account? Log in” in the bottom of the screen

**Comment by darrenvong** [comment] 2021-04-10 21:19
Duplicate of #969

**Closed as completed by darrenvong** 2021-04-10 21:19 UTC
Labels: 1.topic frontend, mobile
